### ISSUE TITLE
Changing source of playing youtube video to an mp4 video doesn't work

### ISSUE THREAD

**Issue by adamtal3** [videojs/videojs-youtube#347]
I've created a video player that can show videos from youtube or mp4 videos.

When the player is loaded on a youtube video, calling src with an mp4 source does nothing.

Example: http://jsfiddle.net/kocca6sb/1/

Can anyone spot the issue with different techs source changing? Is it really youtube plugin related?

**Comment by narration-sd** [comment]
I can give you a work-around -- really what it does is not try to use the youtube tech when playing an mp4. Quite possibly this is something the youtube plugin might  arrange for itself.

I think the proper setup (someone may correct me on this) is that when playing an mp4, we should identify video-js.swf as the tech. This is so the swf player included with video-js will be used as fallback for browsers that don't do mp4 natively.

And naturally you want to be sure your source is labelled with the propermime code.

Here's how that works out:

`<video id='yourid'
        ...rest of your setup...
    data-setup='{"techOrder": ["youtube"]}'>

<source src="https://youtu.be/yourvideocode" type='video/mp4' />

**Comment by gkatsev** [comment]
It looks like the issue is that tech doesn't dispose itself properly and the youtube iframe stays around when the video is changed.

**Comment by gkatsev** [comment]
A new version with this fix is now released.
