### ISSUE TITLE
bufferedPercent method frozen when video is paused

### ISSUE THREAD

**Issue by kudlohlavec** [videojs/videojs-youtube#349]
Hi everyone,

I ran into an issue with this youtube plugin. When working with plain video-js everything works fine, but when im using it with youtube plugin bufferedPercent() method is not working properly - when video is paused, this method doesnt return updated buffered value but still the value from the time when the video was paused. When I hit the play button again, also the value is updating as it should be.
I need to know when the video is completely loaded in the paused state so i also tried readystate function but that is not supported at all.
Can you please give me some assumptions on how to overcome this problem? If it cannot be solved, is there some other way of which i dont know that can tell me that the video is fully loaded?
thanks for responses

**Comment by eXon** [comment]
I'm not sure how the YouTube API is responding to this but I'll take a look if I can solve this.

**Comment by kudlohlavec** [comment]
Thank you very much, looking forward for some news.

**Comment by kudlohlavec** [comment]
Hi eXon, any news on this topic?

**Comment by eXon** [comment]
Let me know if the last version is working fine!

**Comment by kudlohlavec** [comment]
Hi eXon,
thank you for your response. I have tried the newest version but the problem still persists. The only thing that has changed is that bufferedPercent method now returns amount of buffered seconds instead of percents. But it still hangs up when the video is paused - as soon as the play button is being hit again the method returns updated value.
Described behaviour can be seen for example on this page: http://52.3.64.17/vjsExperiment/ . Look into console output where Im printing value returned by bufferedPercent method every second and try pausing and unpausing the video to see this problem in action.
thank you

**Comment by kudlohlavec** [comment]
Hi eXon, I want to kindly ask when do you expect that you can have time to look into this?
thank you

**Comment by gkatsev** [comment]
This should be working in the latest versions if videojs-youtube/videojs.
