### ISSUE TITLE
Youtube play button shows at end of video

### ISSUE THREAD

**Issue by alsar** [videojs/videojs-youtube#360]
When I play a video to the end the youtube play button displays. Then I have to click it first, so that the videojs play button displays.

![selection_003](https://cloud.githubusercontent.com/assets/1380676/12809585/97547990-cb20-11e5-9e71-d4f1381c9796.png)

I use the latest version (2.0.8).

**Comment by vojka** [comment]
I also have the same problem. Is this a bug or is there a switch to turn this behavior off?

**Comment by gkatsev** [comment]
I'm guessing it's a bug and hopefully youtube has an API to prevent that from happening but it's very possible that there's no way of doing it.

**Comment by nhterry** [comment]
I am experiencing the same issue. Clicking the YouTube play button does not then replay the video, but if you click it again, it will then replay the video. In the wild: https://www.bonnieterrylearning.com/video/colored-overlays-reading-help-scotopic-syndrome/

**Comment by gkatsev** [comment]
Not sure there's anything that can be done.
