### ISSUE TITLE
Playback rate button not showing (fix: add property featuresPlaybackRate: true)

### ISSUE THREAD

**Issue by phhu** [videojs/videojs-youtube#366]
The playback rate selector does not show even if the playbackRates option is specified in data-setup

`"playbackRates": [ 0.25, 0.5, 1, 2]`

Videojs only displays the playback rate button if the tech has a property featuresPlaybackRate:

``` javascript
  PlaybackRateMenuButton.prototype.playbackRateSupported = function playbackRateSupported() {
    return this.player().tech_ && this.player().tech_['featuresPlaybackRate'] && this.playbackRates() && this.playbackRates().length > 0;
  };
```

This issue can be fixed by added a property `featuresPlaybackRate: true` to the `Youtube` object in YouTube.js

Since not all youtube videos offer the playback rate option, I'm not sure how to detect this (i think some older ones don't use HTML5 and so don't show the option. I'm not sure of the details.). 

Also it seems that the videojs playback rate control doesn't immediately show the correct playback rate on its main button, although it does work, at least with standard youtube playback rates (0.25, .5, .1, 2,5 I think).

**Comment by gkatsev** [comment]
The videojs button displays what the player is configured with. Would be nice to detect if the youtube video we're playing supports playbackRate and then enable the button with the playback rate options that youtube uses.

**Comment by jkliou** [comment]
Just direct call show() when youtube on ready

> this.player_.controlBar.playbackRateMenuButton.show();

I use videojs-youtube/vjs4

**Comment by gkatsev** [comment]
#403 fixes this. It still requires setting up the playbackrates in the player config.
