### ISSUE TITLE
modestbranding is not working 

### ISSUE THREAD

**Issue by RanaMani** [videojs/videojs-youtube#368]
```html
 <video
            id="vid1" 
            class="video-js vjs-default-skin vjs-big-play-centered automaticCaptions vjs-controls-enabled       vjs-has-started vjs-paused vjs-user-inactive"                        
            controls
            width="640" height="264"
            data-setup='{ "techOrder": [ "youtube"], "sources": [{ "type": "video/youtube", "src": "https://www.youtube.com/watch?v=xjS6SftYQaQ"}], "youtube": { "modestbranding": 1 }}'>
</video>
```

**Comment by gkatsev** [comment]
It sounds to me that `modestbranding` refers to the `youtube` in the youtube control bar, since we're not using their control bar, it's "working" as designed.
Can you elaborate more on what you mean by it not working?

**Comment by delueg** [comment]
I also thought it's not working as the Youtube Logo in the bottom right corner is showing.
I think it is not possible to hide this, right?

**Comment by sanketj14** [comment]
it is possible to remove the logo. as the youtube documentation says

modestbranding 

> This parameter lets you use a YouTube player that does not show a YouTube logo. Set the parameter value to 1 to prevent the YouTube logo from displaying in the control bar. Note that a small YouTube text label will still display in the upper-right corner of a paused video when the user's mouse pointer hovers over the player.

**Comment by gkatsev** [comment]
Yeah, I'm not suer there's anything we can about this.

**Comment by Mrkisha** [comment]
Youtube has `modestbranding` option to hide trademark. However I could not make it work with this plugin.

**Comment by delueg** [comment]
@Mrkisha you can hide it but you can't hide the small logo in the right bottom corner

**Comment by Mrkisha** [comment]
@delueg too bad. Thanks though.
