### ISSUE TITLE
YouTube Pre-loader / Spinner issues on Mobiles

### ISSUE THREAD

**Issue by bwisekal** [videojs/videojs-youtube#369]
We're using videojs on a premium theme of ours for fullscreen video backgrounds and we're experiencing issues with YouTube videos being able to be played on mobile devices.

Our first issue encountered was that specifically on YouTube videos, when having the "big play button" enabled, it would not trigger the YouTube video to play when clicked. Though we managed to come up with a solution that worked by simply removing that button. It wasn't a pretty solution but it did the trick. (note: this is only applied on smaller devices)

Now our next issue is regarding when "autoplay" is enabled. We are very much aware of the fact autoplay will not work on mobile devices, but what it does instead is causes the "preloader / spinner" to constantly show as if it were trying to load the video. After awhile, it displays an error message about being unable to load the video.

Click outside the middle of the video (where the preloader / spinner is) will not play the video, but clicking outside of that (anywhere else on the browser) it will play the video. This is fine and dandy, but it's deceptive to visitors, thinking the video is trying to load but isn't, not knowing that they can click outside it.

This only happens when the "autoplay" is enabled.

Here are two examples we have that will demonstrate the issues faced:

Autoplay enabled: http://www.kingsizetheme.com/home/youtube-fullscreen-background/

Autoplay disabled: http://www.kingsizetheme.com/home/youtube-fullscreen-background-no-ap/

Is there a suggestion or solution already for resolving this issue?

If not, or hasn't yet been reported, do you have any suggestions?

Thanks for your time and insight!

Should also note out that this happens on all mobile devices and browsers tested thus far.

We are also using the latest version of video.js.

**Comment by devsekhar** [comment]
Any update on this?

**Comment by bwisekal** [comment]
Disappointing it's almost been a month since posting it and no response!

**Comment by Magiweb** [comment]
My understanding is that the developer doesn't have much time to continue supporting these plugins (he also created a Vimeo plugin for VideoJS). Someone may be able to convince him to hand over the reigns to another interested party - there's plenty of demand and interest in these plugins! 

What if we just do an agent check in javascript and block autoplay from being allowed to be set in the videojs initialisation if we detect a mobile device is being used? I'll give this a try and see if it helps - don't see why it wouldn't.

Strange thing about the "Big button" issue - I'll see about that while I'm at it. Also sounds like it should be easily fixed...

**Comment by bwisekal** [comment]
Hello @Magiweb!

We had a feeling this wasn't being continued but had a hope someone would offer some insight.

We've been looking into some alternatives but still we'd prefer to use VideoJS. If you think this can be resolved, we'd be most grateful. If you'd like a little financial support for your efforts, feel free to contact me privately. I'm available at hello (at) ourwebmedia.com and we can discuss this more privately but we'd definitely be interested in contributed to an updated version of this. 

It's a great script. A lot of potential in it.

Thanks again for your chiming in on this. We really do appreciate it!

**Comment by gkatsev** [comment]
I wonder if the issue is that the youtube tech is trying to autoplay things itself and so on mobile it's trying to call play on youtube but it can't do that but some code paths still run like putting up the spinner.

Btw, re: maintainership, hopefully, we can get it settled and moved into the videojs org, see https://github.com/videojs/video.js/issues/3065

**Comment by gkatsev** [comment]
Seems like the issue is that our `playOnReady` didn't actually account for android correctly.
