### ISSUE TITLE
Youtube live stream link doesn't work

### ISSUE THREAD

**Issue by amkgo** [videojs/videojs-youtube#383]
The live streaming link like `http://www.youtube.com/c/myname/live` doesn't work.
I can re-use this link every time when I go live. Do you have any plan to support it?

Thanks.
Andrew

**Comment by gkatsev** [comment]
From what I can tell, it should work. I've tried with other live youtube videos and it works. Can't find a working `youtube.com/user/live` link to test with.
going to close for now but we can re-open if it's still an issue.

**Comment by rafalsk** [comment]
I can confirm this to be still (or again) an issue.

**Comment by marianoarga** [comment]
I can confirm this is not working on /c/userchannel/live
