### ISSUE TITLE
Can we specify start and end time of videos in the Youtube embed link?

### ISSUE THREAD

**Issue by vivek1729** [videojs/videojs-youtube#388]
The official [documentation](https://developers.google.com/youtube/iframe_api_reference#loadVideoById) cites that we can specify start and end time of a youtube video using the API and also directly in the URL like so:

```
 https://www.youtube.com/embed/DrZfYbOr6sE?start=25&end=35
```

Would be great if we can do this using this plugin. Great work guys! 👍

**Comment by rhsh85** [comment]
I found this simple tool for customising the start & end time of any youtube videos..
Simply go to the below link http://www.youtubestartend.com
& the generated link can also be shared with your friends or embedded in your website.
Absolutely no need for calculations & all that. Simple as 1,2,3.

**Comment by narration-sd** [comment]
Yes, but I think you will find that the timings don't stick.

If the user starts the video after it stops, it will start at the beginning, not the start point you set; and then play to the end, not stopping at your complete point.

At least that's my experience doing this manually with the url argument sets.

So I think we need a YouTube tech plugin that works, still.

**Comment by gkatsev** [comment]
I made a PR to fix this (https://github.com/videojs/videojs-youtube/pull/422). It's a pretty minimal change, so, the url form won't work. However, if you pass in `start` and `end` times to the youtube options, it should work.

```js
var player = videojs('vid1', {
  youtube: {
    start: 25,
    end: 35
  }
});
```

**Comment by solutionsmith** [comment]
@gkatsev would it be possible to get this to work in url form?

**Comment by narration-sd** [comment]
+10 on this. I am really fatigued of hacking the various plugin sources to get this to work, which fails each time youtube tech is updated -- and is very janky to work with anyway...

Please! and thank you...

**Comment by narration-sd** [comment]
> +10 on this. I am really fatigued of hacking the various plugin sources to get this to work, which fails each time youtube tech is updated -- and is very janky to work with anyway...
> 
> Please! and thank you...

Ah, apologies -- I look above and see I missed that you did give a way around the plugins already. So url properties would be just a convenience, if a nice one.

Looking forward to trying the new ability out, in any case -- really thanks, Gary @gkatsev

**Comment by genoa21** [comment]
Sorry I am not really that star trek in codes, but where do I add this javascript in the youtube options? I wanted to use a stop on a background video in a wordpress page.

Thank you.

**Comment by Rinkuk1993** [comment]
Added support for URL start and end time in seconds - https://github.com/videojs/videojs-youtube/pull/511

**Comment by gkatsev** [comment]
Thanks @Rinkuk1993! This is now out in 2.6.0.

**Comment by youtubeissue** [comment]
Yes, it is possible just go throw this link https://newslib.com/youtube-not-working/ and follow all steps one by one. Surely you will get your solutions. May it works.

Thank You.
