### ISSUE TITLE
Not a issue But suggestion for Vimeo

### ISSUE THREAD

**Issue by onigetoc** [videojs/videojs-youtube#389]
The old Vimeo plugin do not work with the latest Videojs. 
https://github.com/videojs/videojs-vimeo
It would be great to do a Vimeo plugin based on your Youtube plugin.
There's a api for Vimeo
https://developer.vimeo.com/player/js-api
Here a way to remove with css all Vimeo Control.
http://www.cssplay.co.uk/menu/cssplay-vimeo-hide-control-bar.html
Vimeo API example.
https://github.com/vimeo/player-api
And this jquery video control is very powerfull.
https://github.com/dachcom-digital/jquery-video

**Comment by gkatsev** [comment]
Thanks for the feedback. The vimeo plugin is already pretty similar and keeping them more inline would be nice.

**Comment by onigetoc** [comment]
The vimeo plugin do not work since the Videojs update

**Comment by onigetoc** [comment]
allez Benoit Tremblay un petit effort, Dailymotion ne marche plus non plus depuis le dernier videojs
https://github.com/benjipott/video.js-dailymotion :)
