### ISSUE TITLE
Mobile click/tap events behave differently compared to native videojs player

### ISSUE THREAD

**Issue by NemSavic** [videojs/videojs-youtube#390]
Whenever you click/tap the video player on a mobile device it triggers pause/play, whereas the native videojs player instead displays the video controls. I wasn't sure if this was intentional behaviour or a minor issue.

For my implementation I'm running both YouTube and MP4 videos on iPads and ideally the video player would function the same. Any feedback or advice to help me accomplish this is greatly appreciated.

I created a quick sample in the codepen below, if you use chrome to simulate an iPad you can replicate the behaviour in your browser.

http://codepen.io/nsavic/pen/BzQXab?

**Comment by gkatsev** [comment]
Seems like this is a youtube limitation. There isn't a way to disable that behavior from their API. It's might be possible to have a workaround by inserting another element in front of the youtube iframe to capture these clicks to toggle the controls. Would you be interested giving such a PR a shot?

**Comment by LuaTenshi** [comment]
I'm having the exact opposite problem. Tap to play works on my computer, but not on my phone... https://i.mirai.red/RnXXh.webm
