### ISSUE TITLE
How to call iv_load_policy with javascript only

### ISSUE THREAD

**Issue by onigetoc** [videojs/videojs-youtube#392]
I looking for to find out, how to add the iv_load_policy only in javascript

`"youtube": { "iv_load_policy": 3 }`

When i put the iv_load_policy into html it work, but not called with javascript.

I call my player this way.

```
vgsPlayer.src({
    "techOrder": ['youtube'],
    "type": "video/" + ext,
    "src": vidURL
  });
```

**Comment by gkatsev** [comment]
How are you configuring the player? You should be able to do it like so:
```js
var player = videojs('vid1', {
  youtube: {
    iv_load_policy: 3
  }
});
```
Or
```html
<video controls data-setup='{"youtube": { "iv_load_policy": 3}'>
```

If that doesn't work, could you provide a [reduced test case](https://css-tricks.com/reduced-test-cases/)? It would make it a lot easier for us to reproduce the issue you are experiencing and thus fixing it.

**Comment by onigetoc** [comment]
Like i said, your first exemple do not work, but the second do.

**Comment by onigetoc** [comment]
I tryed many time and the javascript way work but not when adding to a page like this.
```
<video
  id="vid2"
  class="video-js vjs-default-skin"
  controls
  width="640" height="264"
  data-setup='{ "techOrder": ["youtube"], "sources": [{ "type": "video/youtube", "src": "https://www.youtube.com/watch?v=xjS6SftYQaQ"}], "youtube": { "iv_load_policy": 1 } }'
></video>
```
in this video, there's a annotation at top between 2 and 15 seconde at the start of the video

**Comment by onigetoc** [comment]
Ok, sorry, i think it's working now
