### ISSUE TITLE
Fullscreen do not work on IOS

### ISSUE THREAD

**Issue by onigetoc** [videojs/videojs-youtube#396]
Fullscreen do not work on IOS. 
I think there's a api from youtube for fullscreen but i'm not sure.

If it's not possible, i think we should find a way to disable videojs on IOS.

**Comment by gkatsev** [comment]
I can confirm this.

**Comment by gkatsev** [comment]
Looking at this some more, it's not really possible to do anything without disabling our custom controls and enabling youtube's controls on iOS. The youtube iframe API doesn't provide any fullscreen functionality.
I don't think we want to do that by default but I believe it's possible to do it via options.

**Comment by gkatsev** [comment]
You can configure the tech to use the youtube controls. See the example here: https://github.com/videojs/videojs-youtube/blob/d9d2a57752d55172f49e3c97a27a6ccb5b13d4a6/examples/youtube-controls.html#L11

```js
var player = videojs('vid1', {
  youtube: {
    ytControls: 2
  }
});
```

Hope that helps.

**Comment by onigetoc** [comment]
I alway see the Videojs control over youtube control. 
I guess we should remove the control on the setting or make the control bar display none.

May be just with css.
```
.vjs-controls-disabled .big-play-button, .vjs-controls-disabled .vjs-control-bar {
    display: none !important;
}

```

**Comment by gkatsev** [comment]
In my testing, I did not see the videojs control bar when `ytControls` were set.

**Comment by zivkaziv** [comment]
Hi guys, I'm facing this issue as well.
Do you have any other solution that might work in 2019?
