### ISSUE TITLE
Play video on mobile with Videojs control

### ISSUE THREAD

**Issue by thaihoc2** [videojs/videojs-youtube#398]
Hi guys ,

I have an issue when display youtube videos with poster on mobile ( tested on iphone 6 and Samsung S5)
I tested with sample code :
```html
    <video id="vid1"
           class="video-js vjs-default-skin"
           controls
           poster="../App_Themes/img/all-weather.png"
        width="640" height="264"
        data-setup='{ "techOrder": ["youtube"], "sources": [{ "type": "video/youtube", "src": "https://www.youtube.com/watch?v=RBumgq5yVrA"}] }'>
    </video>
```
It worked well on desktop and not in mobile . If i remove "controls" it will be work , but i can't display poster image.

Could you give me some advice in this case ?

**Comment by gkatsev** [comment]
The controls/poster thing is a videojs issue: https://github.com/videojs/video.js/issues/1625
As for the controls showing up and having this work on mobile, it's all working for me.
