### ISSUE TITLE
Can not play youtube on android mobile browser

### ISSUE THREAD

**Issue by csuntitle** [videojs/videojs-youtube#402]
I'm try to use videojs-youtube on android mobile. It's output only sound but not video ( Other functions are work ). What should I do for this problem

example code
```
<video
    id="vid1"
    class="video-js vjs-default-skin"
    controls
    autoplay
    width="640" height="264"
    data-setup='{ "techOrder": ["youtube", "html5"], "sources": [{ "type": "video/youtube", "src": "https://www.youtube.com/watch?v=XXXXXXX"}] , "customControlsOnMobile": true }'

>   </video>
```
Thank for all the answers.

**Comment by gkatsev** [comment]
It's working for me with latest chrome, videojs, and videojs-youtube. Closing, but we can re-open if a reduced test case is provided.
