### ISSUE TITLE
latest build doesn't seem to have the dist folder

### ISSUE THREAD

**Issue by designerwhocodes** [videojs/videojs-youtube#404]
Hi,

Can you please point me to the JS and CSS files used in the examples. Unable to find in latest build.

Thanks, Pat

**Comment by gkatsev** [comment]
They're available on npm or in the [tag](https://github.com/videojs/videojs-youtube/tree/v2.1.0) in the `dist/` folder

Hope that helps.

**Comment by designerwhocodes** [comment]
I pulled the latest through bower but using Youtube JS file in there throws error Uncaught SyntaxError: Unexpected token <

**Comment by designerwhocodes** [comment]
I grabbed the one in that folder and still getting error of Uncaught SyntaxError: Unexpected token < when I comment out this JS file no error. Any ideas?

**Comment by gkatsev** [comment]
Not sure. It seems to be installing fine locally.

**Comment by gkatsev** [comment]
Bower is complaining about the main file pointing at a minified file and that there's a version mismatch (between the tag and the bower.json files) but still installs correctly.
