### ISSUE TITLE
Player breaks if video is not available

### ISSUE THREAD

**Issue by dnish** [videojs/videojs-youtube#407]
Hi,
I'm having some issue with the YouTube plugin. I'm using it with the Playlist plugin and everything works fine until one of the videos isn't available anymore (f.e. if it was removed). I get the following error:

```
VIDEOJS: ERROR: (CODE:Unable to find the video undefined) 
Uncaught TypeError: Cannot read property 'cueVideoById' of null
```

The whole player breaks and I'm not able to play one of the other videos anymore.

**Comment by gkatsev** [comment]
If I'm understanding it correctly, this issue will be fixed when https://github.com/videojs/videojs-youtube/issues/419 is fixed. Or at least work better, I'd hope.

Do you have handy access to such a broken playlist?
