### ISSUE TITLE
cannot dispose of youtube player in IE 10, 11, throws Object doesn't support property error.

### ISSUE THREAD

**Issue by sanketj14** [videojs/videojs-youtube#408]
Hi,

I am working in SPA environment, and using the youtube plugin for youtube videos.  I am setting up video js dynamically, passing the youtube source & other stuff from js. 
```
this.videoInfo = {
        id: 'video-'+ r1.id,
        sources: [{
          type: 'video/youtube',
          src:  r1.fileName,
        }],
        thumbnail: r2.fileName,
      };
      var templates = this.app.templateAdapter.getTemplate('components/video-01/video');
      this.videoTemplate = templates(this.videoInfo);
this.$videoJsPlayer = videojs(this.videoInfo.id, {"techOrder": ["youtube"], "height": "720px"});
```
things are working fine in all other browsers, except IE 10 & 11 (surprisingly enough In **IE9** as well!). IE 11 and 10 both throw this error. **Object doesn't support property or method 'stopVideo'**. I investigated in the codes, it lead me to `this.ytPlayer.stopVideo()` in `dispose` function from youtube plugin, apparently the *ytPlayer* instance does not have *stopVideo* method. am I missing something? any help would be greatly appreciated!

Thanks!

**Comment by sanketj14** [comment]
Hey, 
just to let you know, I solved it! apparently the dispose function makes use of native JS `remove` function to remove the youtube-player element, which is not supported by IE. strangely enough it still worked for IE9 but replacing the line with `this.el_.parentNode.removeChild(this.el_);` solved it for me. I even tested it for cross browser, it works flawlessly. 
Thanks!

**Comment by gkatsev** [comment]
Thanks for getting back to us. Looks like it's this line: https://github.com/videojs/videojs-youtube/blob/master/src/Youtube.js#L80
Would you be able to submit a PR for this? Would be greatly appreciated.

**Comment by sanketj14** [comment]
@gkatsev 

Sure! I submitted a PR already at the time of writing this comment.
Thanks for this awesome plugin.

Regards

**Comment by gkatsev** [comment]
Reviewed, and merged. Thanks @sanketj14.

**Comment by gkatsev** [comment]
A release should happen *soon*.
