### ISSUE TITLE
Are we able to add webkit-playsinline?

### ISSUE THREAD

**Issue by dnish** [videojs/videojs-youtube#412]
Hey,
I'm just wondering if we are able to add <code>webkit-playsinline</code>? Just tried to add it on the main video element, but the video goes everytime fullscreen on iOS.

**Comment by gkatsev** [comment]
This is most likely something that youtube needs to either provide an API for or just include by default themselves. We load in the youtube API which loads in the video in an iframe, so, there isn't much we can do.

**Comment by cerebroo** [comment]
Set `"playsinline": 1` like in below code and it will work perfect on iOS 10 iPhone/iPad.
`<video
  id="vid1"
  class="video-js vjs-default-skin"
  controls
  autoplay
  width="640" height="264"
  data-setup='{ "techOrder": ["youtube"], "sources": [{ "type": "video/youtube", "src": "https://www.youtube.com/watch?v=xjS6SftYQaQ"}], "youtube": { "playsinline" : 1} }'
>
</video>
 `

**Comment by gkatsev** [comment]
Looks like `playsinline` is now an [official](https://developers.google.com/youtube/player_parameters#playsinline) option.

**Comment by mfprogrammer** [comment]
Can the youtube player work on the mobile site and not on a app. 
i want the video to play on my website and inline. Is that possible?
