### ISSUE TITLE
Can't get it to work in ReactJS

### ISSUE THREAD

**Issue by c0debreaker** [videojs/videojs-youtube#413]
Will it work with ReactJS? I saw it worked one time but the video only showed for a second then it disappeared. Never I saw the youtube video again.

**Comment by gkatsev** [comment]
It should work with react, though, you'd need to tell react that the div that videojs uses is going to get updated and that react shouldn't do anything about it. For example, wrapping it in a component that returns `false` from `shouldComponentUpdate`.
I'm going to note that this is something we should write a guide about.

**Comment by c0debreaker** [comment]
Thanks a lot. I can wait.

**Comment by c0debreaker** [comment]
I got it working!!! It was tough!!! I didn't use shouldComponentUpdate

**Comment by c0debreaker** [comment]
Here are more updates. The first time I load it after clicking `Watch Now` button, this is what I have in DOM - http://i.imgur.com/EwDpRYJ.png

After I close the player and then click `Watch Now` button again, this is what I have. Tons of DOM elements are gone - http://i.imgur.com/Sw2mXJ9.png

Why is it doing this?

Here is the code - https://gist.github.com/c0debreaker/01f3962fedaea8cbb27b3145db03157e

**Comment by gkatsev** [comment]
I think that's exactly the problem that `shouldComponentUpdate` is fixing. If anything in the DOM changes, React will reload the entire component which will cause the player to break since videojs won't run again.

**Comment by c0debreaker** [comment]
I had `return false` in shouldComponentUpdate of my NoUpdate component. I wrapped the video code like this

```
<NoUpdate>
  <video> .........</video>
</NoUpdate>
```

However, when I do that, the Modal is blank. Look at my latest code thought I changed line 46 for now to point to my mp4 player rather than youtube player.

https://gist.github.com/c0debreaker/d4a2ed270e517fb4ebe14432e1ae0161

**Comment by c0debreaker** [comment]
This is how I wrote NoUpdate.js - https://gist.github.com/c0debreaker/986376be2c5486e43ee604bc62b49deb

**Comment by c0debreaker** [comment]
I got it working using the logic from this link - https://github.com/esportsguy/react-videojs/blob/master/src/index.js
