### ISSUE TITLE
Youtube error not printed by videojs

### ISSUE THREAD

**Issue by albertogasparin** [videojs/videojs-youtube#419]
Videojs has a built in function that shows errors on an overlay. 
In order to do that the tech must provide an error `code` *and* an error `message` properties.  However, `videos-youtube` currently uses `code` property as message and does not set `message`.
As a result no error text is shown to the user.

Changing error mapper code to something like this would improve default experience:
``` js
case 5:
  return { code: 'YT' + this.errorNumber, message: 'Error while trying to play the video' };
// case...
```

Moreover, the spinner is not removed on error. `videos-youtube` should trigger `this.trigger('pause')` before triggering the `error` event in `onPlayerError()` so the spinner will be removed. You can see the issue by using a video that cannot be embedded. 

Tested with videojs v5.14.1 and videojs-youtube v2.2.0
Happy to make a PR to solve these bugs

**Comment by gkatsev** [comment]
Sounds good to me. If you can make a PR, that would be great.
