### ISSUE TITLE
No compatible source was found for this media.

### ISSUE THREAD

**Issue by newtocoding123** [videojs/videojs-youtube#420]
Hi, 
I used the code from the Example and somehow, it just doesnt work. I've installed it and I'm on desktop Chrome using Apache. idk if i missed any steps?

**Comment by gkatsev** [comment]
Can you please elaborate on "doesn't work"? Also, how did you install and run this? Any errors in the developer tools console?

**Comment by newtocoding123** [comment]
Okay, there are 2 kinds of ways it doesn't work. 

**1st =** 
It only shows a player and nothing else. No video comes out at all. 
I installed using "npm install videojs-youtube" via the cmd! Have all the files in the node_modules folder. I run both methods, directly opening the html file on chrome as well as using Apache localhost to open it. Both only shows the player but can't play videos. Directory are all linked to files in the node_modules as well. The files are in the correct directory. Am i missing anything? 

3 errors:
file:///C:/xampp/htdocs/fyp/HTML%20Page/Users/Zijie/node_modules/video.js/dist/video-js.min.css Failed to load resource: net::ERR_FILE_NOT_FOUND
file:///C:/xampp/htdocs/fyp/HTML%20Page/Users/Zijie/node_modules/video.js/dist/video.min.js Failed to load resource: net::ERR_FILE_NOT_FOUND
file:///C:/xampp/htdocs/fyp/HTML%20Page/Users/Zijie/node_modules/videojs-youtube/dist/Youtube.min.js Failed to load resource: net::ERR_FILE_NOT_FOUND


**2nd =** If my directory for Youtube.min.js is linked to a folder in the same place as my html page i created, it shows a black screen with a cross and "No compatible source was found for this media. "

errors: 
Uncaught SyntaxError: Unexpected token <
video.min.js:18 VIDEOJS: ERROR: The "Youtube" tech is undefined. Skipped browser support check for that tech.
c.logByType @ video.min.js:18
video.min.js:18 VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) No compatible source was found for this media. d


Appreciate your help!

**Comment by gkatsev** [comment]
Are you trying to run the examples in the [`examples` folder](https://github.com/videojs/videojs-youtube/tree/master/examples)? If so, you probably want to clone the repo, go into it and run `npm install`, then run `npm run build` to rebuild the latest version of videojs-youtube. Then, if you open up the examples, it should work -- that's how I test it when working on it. (Or you could go into `node_modules/videojs-youtube` and run `npm install` there without cloning).

If you're trying to use it in a project, you'd either need to install `videojs-youtube` and `video.js` in your project and then in your HTML page, you'd want to link to both vjs-youtube and vjs files:
```html
<script src="node_modules/video.js/dist/video.js"></script>
<script src="node_modules/videojs-youtube/dist/Youtube.js></script>
<link href="node_modules/video.js/dist/video-js.css" rel="stylesheet">
```

Hope that helps. Going to close the issue but we can continue the discussion even if it's closed.

**Comment by newtocoding123** [comment]
Alright, I'll try to make the examples work first. Sorry, but i'm really new to all these codings and stuff. So how do I go about doing this:"(Or you could go into node_modules/videojs-youtube and run npm install there without cloning)." Are u able to provide more detailed steps for me? like so i use CMD and type in npm install or something?
Because I thought I have already installed it since i have all your videojs-youtube files in the node_modules folder.

**Comment by newtocoding123** [comment]
Alright, so i've managed to get the examples working thanks a lot! So i'm actually doing a project that requires it to play 360 videos without click and drag, simply a mouse hovering over and video will turn. So i was wondering if i could implement any option in video.js-youtube to disallow click and drag and video will turn when playing 360 videos?

**Comment by gkatsev** [comment]
Is that 360 support something that youtube offers natively?

**Comment by newtocoding123** [comment]
Yep! Youtube has 360 videos support. I tried and i can currently play 360 videos with video-js youtube. Just that i'm finding a way to disable click and drag with youtube because i use [https://github.com/yanwsh/videojs-panorama](https://github.com/yanwsh/videojs-panorama) as well. It allows click and drag to be disabled. i'm wondering if **video-js youtube** and **videojs-panorama** can be combined to allow videojs-panorama to play videos using youtube tech.

**Comment by gkatsev** [comment]
If youtube supports either click-to-drag or mouse hover following, then I think that it makes sense for us to have an option for that s well.

I think what vjs-panorama does is a bit too much to be able to work with vjs-youtube without a lot of work on their (or our) parts.
