### ISSUE TITLE
Playlist with MP4 and YouTube

### ISSUE THREAD

**Issue by Ande1232** [videojs/videojs-youtube#425]
Hi!
Is possible to create a playlist with MP4 and youtube's videos? Finished an MP4 movie, it must start automatically a youtube video

**Comment by gkatsev** [comment]
Yup, that should work with videojs-youtube. You'd need to use something like [`videojs-playlist`](https://www.npmjs.com/package/videojs-playlist) to manage the playlist but you should be able to have an mp4 and a youtube video in the list.
