### ISSUE TITLE
issue with videojs@5.15.1

### ISSUE THREAD

**Issue by revolunet** [videojs/videojs-youtube#427]
hey

had some trouble make `videojs-youtube@2.3.0` work with `videojs@5.15.1` - works fine when upgrading to `videojs@5.16` though which is great.

when using `videojs(selector, options, cb)`  and 

```js
sources: [{
  src:  'http://youtu.be/T2L9IMC4r7Q',
  type: 'video/youtube'
}]
```

i get "VIDEOJS: ERROR: The "Youtube" tech is undefined. Skipped browser support check for that tech."

looks like videojs is trying to load the source while the youtube iframe_api is not ready yet, and the Youtube Tech constructor, is not executed.

same when using source node : 
```html
<source src='http://youtu.be/T2L9IMC4r7Q' type='video/youtube' />
```

i noticed it works when using <script> tags (http://jsbin.com/wosamovozi/1/edit?html,output) but not with npm

tell me if you need further details.

**Comment by gkatsev** [comment]
From slack: it appears to work via script tags with 5.15 but fails when using a bundler like webpack.

**Comment by revolunet** [comment]
we can close its been fixed

**Comment by gkatsev** [comment]
Sounds good.

**Comment by rukai-kooboo** [comment]
Hi @revolunet, I meet this problem too when I'm using it with NPM in a Vuejs project.
Will you share the solution to us? It is great and kind of you. Thanks!

**Comment by revolunet** [comment]
Hi, i dont remember exactly but i guess some videojs update fixed it meanwhile
