### ISSUE TITLE
Can't able to load youtube video from angular directive

### ISSUE THREAD

**Issue by sanjib-dev** [videojs/videojs-youtube#429]
here is my code
---in controller
`...
$scope.videoUrl = $sce.trustAsResourceUrl(unit.filecontent.unit_url_new)
...`
in html
`<video
                                ng-if="isYoutube !== 0;"
                                id="vid1"
                                class="video-js vjs-default-skin"
                                controls
                                autoplay
                                width="640" height="264"
                                vjs-video
                                vjs-setup='{ "techOrder": ["youtube"], "sources": [{ "type": "video/youtube", "src": "{{videoUrl}}"}] }'
                              >
                              </video>`

this shows MediaError {message: "Unable to find the video"}
when i give link on html page directly, it works. so the directive and all library files are loaded properly I thik. please help me on this.

**Comment by zfarrugia** [comment]
Having the same issue.

**Comment by zfarrugia** [comment]
I was able to work around the issue by creating a directive in between then running the video.js setup manually.

> If you don't want to use automatic setup, you can leave off the data-setup attribute and initialize a <video> element manually using the videojs function:
> - https://github.com/videojs/video.js

I implement the directive as a modal containing the video.js, so most of my code isn't relevant here.
But the base idea is functional.

```
var url = "https://www.youtube.com/watch?v=XXXXXX"
var options = {
    "techOrder": ["youtube"],
    "sources": [{"type": "video/youtube", "src": url, "youtube": { "ytControls": 2, "customVars": { "wmode": "transparent" } }}]
};

var player = videojs('vid-player', options, function onPlayerReady() {
    videojs.log('Your player is ready!');

    //this.play(); // Autoplay
    
    this.on('ended', function () {
        videojs.log('Player Destroyed!');
    });
});
```
Remember to clean up the player when its no longer used `player.dispose()`.

Hope this info can be of some help.

Zac

**Comment by sanjib-dev** [comment]
Thanks for the reply. will try this

**Comment by sanjib-dev** [comment]
works like a charm..thanks

**Comment by sanjib-dev** [comment]
managed to load the video but clicking on next video does not load the video :(  
in console player instance is correctly logged..whats i am doing wrong?

**Comment by zfarrugia** [comment]
Are you able to describe the "next video" scenario? Examples might help better understand the issue better.

**Comment by sanjib-dev** [comment]
I have a list of videos to be played which have both self hosted videos and youtube videos in the same list. now when I start a video which is a self hosted one and then try to play a youtube video in the same videojs instance, its not able to play it.

**Comment by sanjib-dev** [comment]
My issue is still not solved. Can you help me on this please. I am not using playlist as every video must be loaded after user choose(click) to view it

**Comment by sanjib-dev** [comment]
I managed to finally solved this :)
Thanks for your time and advise

**Comment by henriquecholo** [comment]
Hey,

Could you past some of the code so i can fix mine?
