### ISSUE TITLE
Loading Youtube video in the same player do not show the right poster

### ISSUE THREAD

**Issue by onigetoc** [videojs/videojs-youtube#433]
Loading Youtube video in the same player do not show the right poster.
If i use javascript to load another Youtube video we see the poster of the first video loaded before.

The new Youtube poster never show during the loading time.

```
$('#vidlink a').on('click', function (e) {

e.preventDefault();
var player = window.player = videojs('vid1');

var vidlink = $(this).attr('href');

player.src({
   src: vidlink ,
   type: getType(vidlink )
 });

})
```

**Comment by varemenos** [comment]
The poster of the new video doesn't load because of the way the poster loading was written.

```

      if (!this.options_.poster) {
        if (this.url.videoId) {
          // Set the low resolution first
          this.poster_ = 'https://img.youtube.com/vi/' + this.url.videoId + '/0.jpg';
          this.trigger('posterchange');

          // Check if their is a high res
          this.checkHighResPoster();
        }
      }
```
https://github.com/videojs/videojs-youtube/blob/master/src/Youtube.js#L395-L404

As you see, they check whether the poster option is not set, if that's true they go ahead and add a value to it and load the video's poster. This won't work the next time though because they have set the poster option's value. To make it work (for now at least) is to unset the poster value before loading the next video.

**Comment by onigetoc** [comment]
Hi @varemenos 
How to unset the poster?

**Comment by varemenos** [comment]
I'm not certain  myself but I'd say something like

```
this.options_.poster = undefined;
```

**Comment by gkatsev** [comment]
So, looking into this, I think we want to keep the behavior as is.
However, you can unset the poster by passing in an empty string to the `poster()` method, before changing to the youtube video:
```js
player.poster('');
player.src({src: 'https://www.youtube.com/watch?v=xjS6SftYQaQ', type: 'video/youtube'});
```

I added an example that you can see how it works: https://github.com/videojs/videojs-youtube/pull/445

Hope that helps.

**Comment by onigetoc** [comment]
If you have the Youtube ID why not switch to the right poster?
`player.poster('https://img.youtube.com/vi/xjS6SftYQaQ/maxresdefault.jpg');`

**Comment by gkatsev** [comment]
videojs-youtube will actually try to do that for you. You just might need to unset the previous poster if you're switching from say an mp4 with another poster to a youtube video.

**Comment by varemenos** [comment]
Even when switching between Youtube videos you need to unset the previous Youtube video's poster
