### ISSUE TITLE
videojs object errors

### ISSUE THREAD

**Issue by nsteinfeld** [videojs/videojs-youtube#434]
I have been using this plugin for 3 years, but just recently noticed that dist/Youtube.js is throwing a lot of errors which all seem to be related to the videojs object. videojs.browser.IS_IOS is throwing an error so is videojs.getTech('Tech') etc. I have tested the newest release of this plugin and got the same result. Has there been a recent update for the videojs that affects now this plugin?

Uncaught TypeError: videojs.getTech is not a function
    at videojs-youtube.js:50
    at videojs-youtube.js:31
    at videojs-youtube.js:33

**Comment by gkatsev** [comment]
It seems like you're using a too-old version of videojs. What version are you using?

**Comment by nsteinfeld** [comment]
Is the videojs object deprecated?
If it is deprecated: We have been using this VideoJS share plugin (https://github.com/dmlap/videojs-share) and it is throwing errors that have to do with the videojs object in conjunction with videojs version 6. We used this plugin for the past three years without any problems, it provided social media sharing, embed codes, and share link all in one overlay screen. Anything similar out there?

**Comment by gkatsev** [comment]
You probably shouldn't update to video.js 6 quite yet. And you might want to downgrade the version of videojs-youtube you're using to have support for the version of videojs you're using.

**Comment by nsteinfeld** [comment]
Ok, I went back to the README of that video-youtube version and it does say to "Use branch `vjs4` if you still using old VideoJS `v4.x`." I haven't upgraded anything in three years, and I was still using cdn version 4.5. So what are all those errors all of a sudden? Should this still be working?

**Comment by gkatsev** [comment]
Seems like you updated videojs-youtube to a version incompatible with the version of videojs you are using.

**Comment by nsteinfeld** [comment]
Thanks. I got it to work.

**Comment by ugonnanwosu** [comment]
@nsteinfeld Can you please give some details on how you resolved your issue? What versions of videojs and videojs-youtube did you use to ensure compatibility?

**Comment by spmsupun-certscanner** [comment]
@gkatsev  I am getting the same error only in the production build, any idea?
