### ISSUE TITLE
Server Side Rendering document is undefined

### ISSUE THREAD

**Issue by 0xsven** [videojs/videojs-youtube#435]
I am working on an app that uses server side rendering (aka. universal app).

By importing videojs-youtube it tries to inject something into the body. Unfortunately this doesn't work on the server since there is no document. 

Is there a way to self initialize the library?

**Comment by 0xsven** [comment]
Created a pull request that should solve it

https://github.com/videojs/videojs-youtube/pull/436

**Comment by gkatsev** [comment]
Thanks!
