### ISSUE TITLE
Video is simply not showing up, only audio

### ISSUE THREAD

**Issue by manuelro** [videojs/videojs-youtube#440]
**Versions:**
`Video.js: 5.11` and `Youtube plugin: 2.3.2`.

I am loading Video.js from the CND:
```javascript
<script src="//vjs.zencdn.net/5.11/video.min.js"></script>
```

And the Youtube plugin from another CDN:
```javascript
<script src="https://cdnjs.cloudflare.com/ajax/libs/videojs-youtube/2.3.2/Youtube.min.js"></script>
```

I'm loading these async, since I plan to use the JS Api to set the video src. But all I get are some disabled controls. When I call the `this.play()` function, the video plays but only the audio gets played.

**The video tag**
```html
<video id="videoarea" class="video-js vjs-default-skin" controls preload="auto" width="640" height="264"></video>
```

**The Javascript code**
```javascript
videojs( 'videoarea', {
      techOrder: [ 'youtube', 'html5' ],
      preload: 'auto'
    } ).ready( function() {
      this.src( [{ type: 'video/youtube', src: 'https://www.youtube.com/embed/y6Sxv-sUYtM' }] );
      this.play();
    } );
```

**The result**
![image](https://cloud.githubusercontent.com/assets/4284074/24817493/e992fe28-1b99-11e7-87d2-eb9def40d746.png)

I googled a better explanation of the API but what I found is certainly lacking. Any ideas of why this is?

**Comment by manuelro** [comment]
UPDATE: Make sure to use unique IDs, or your browser will have problems finding out where to insert the iFrame.

**Comment by maryam-abdullah** [comment]
how were you able to solve this issue?
