### ISSUE TITLE
ytControls issue - "doubled up" with html5 controls 

### ISSUE THREAD

**Issue by justinlevi** [videojs/videojs-youtube#441]
How do you get the default videojs play button to display but then use the native Youtube controls (ytControls)? 

---

The `examples/youtube-controls.html` does not show any controls by default which seems like it maybe is a bug?? 

![screen shot 2017-04-11 at 11 26 37 am](https://cloud.githubusercontent.com/assets/1117989/24916986/c402296e-1ea9-11e7-8c18-8ba29b0f6073.jpg)

```
<!DOCTYPE html>
<html>
<head>
  <link type="text/css" rel="stylesheet" href="../node_modules/video.js/dist/video-js.min.css" />
</head>
<body>
  <video
    id="vid1"
    class="video-js vjs-default-skin"
    width="640" height="264"
    data-setup='{ "techOrder": ["youtube"], "sources": [{ "type": "video/youtube", "src": "https://www.youtube.com/watch?v=xjS6SftYQaQ"}], "youtube": { "ytControls": 2 } }'
  >
  </video>

  <script src="../node_modules/video.js/dist/video.js"></script>
  <script src="../dist/Youtube.js"></script>
</body>
</html>
```

If I add the `controls` attribute to the video element the big play button displays as expected, but after you click the play button, both the videojs default-skin controls and the youtube native controls display. 

![screen shot 2017-04-11 at 11 28 57 am](https://cloud.githubusercontent.com/assets/1117989/24917104/17629bf2-1eaa-11e7-8417-2e95afafac62.jpg)

```
  <video
    id="vid1"
    class="video-js vjs-default-skin"
    width="640" height="264"
    controls
    data-setup='{ "techOrder": ["youtube"], "sources": [{ "type": "video/youtube", "src": "https://www.youtube.com/watch?v=xjS6SftYQaQ"}], "youtube": { "ytControls": 2 } }'
  >
  </video>
```

![screen shot 2017-04-11 at 11 29 37 am](https://cloud.githubusercontent.com/assets/1117989/24917140/31b94762-1eaa-11e7-9cc0-2d9fde86e077.jpg)

Note the doubled up youtube and videojs controls in the screen grab above. 

What I would expect is that if we specify `ytControls: 2` that the videojs control bar would not be visible during playback. 

I'm very likely missing something... Thanks!

**Comment by justinlevi** [comment]
Note that in the last screen shot above I believe the controls are in the middle of fading out. The videojs controls actually show in front of the youtube controls

**Comment by justinlevi** [comment]
This kind of does what I'm looking for but feels a bit "hackish". Wondering if there is a more official way to handle the problem.

![screenflow](https://cloud.githubusercontent.com/assets/1117989/24921311/617dd810-1eb8-11e7-9c81-7843e80e4a5f.gif)

```
<!DOCTYPE html>
<html>
<head>
  <link type="text/css" rel="stylesheet" href="../node_modules/video.js/dist/video-js.min.css" />
</head>
<style type="text/css">
  .video-js.vjs-default-skin.vjs-paused .vjs-big-play-button {display:block !important;}
</style>
<body>
  <video
    id="vid1"
    class="video-js vjs-default-skin"
    width="640" height="264"
    data-setup='{ "techOrder": ["youtube"], "sources": [{ "type": "video/youtube", "src": "https://www.youtube.com/watch?v=xjS6SftYQaQ"}], "youtube": { "ytControls": 2 }, "nativeControlsForTouch": true }'
  >
  </video>

  <script src="../node_modules/video.js/dist/video.js"></script>
  <script src="../dist/Youtube.js"></script>
</body>
</html>
```

**Comment by gkatsev** [comment]
The youtube-controls example should be showing the native youtube controls and not the videojs controls. On mobile, (at least iOS), it'll end up using the native control bar.

It seems to be working as expected for me.

**Comment by wells** [comment]
@justinlevi The following config works on version `2.0.8` of this plugin and videojs version `5.20.4`.

The key is to specify only the MedaLoader in the children array and set the default controls to false.

```
data-setup='{ "controls": false, "fluid": true, "children": ["MediaLoader"], "techOrder": ["youtube"], "youtube": { "ytControls": 2 } }'
```
