### ISSUE TITLE
where is this file????????

### ISSUE THREAD

**Issue by LedzCop** [videojs/videojs-youtube#461]
<script src="../node_modules/video.js/dist/video.min.js"></script>

how to downoad this file???

**Comment by Henry-Varro** [comment]
You can use this links or download them and put them in your folder
http://vjs.zencdn.net/5.19/video-js.min.css
http://vjs.zencdn.net/5.19/video.min.js

**Comment by gkatsev** [comment]
After cloning, you should run `npm install`, it'll install video.js into `node_modules` and will be available to run your examples. alternatively, you can update the HTML to the urls that were linked above.
