### ISSUE TITLE
Need help for Videojs and Dailymtion for version 5.0+

### ISSUE THREAD

**Issue by onigetoc** [videojs/videojs-youtube#476]
Hi, 
I need help and contributors to create a working version for video.js 5.0+
This is a very basic version

I started a new project here:
https://github.com/onigetoc/videojs-5.0-dailymotion

**Comment by gkatsev** [comment]
Answered in https://github.com/videojs/video.js/issues/4810

**Comment by onigetoc** [comment]
And this is my answer.
https://github.com/videojs/video.js/issues/4810#issuecomment-351170714
