### ISSUE TITLE
useless condition statement

### ISSUE THREAD

**Issue by mysuf** [videojs/videojs-youtube#491]
This call seems to be useless as muted method does not accept any arguments: https://github.com/videojs/videojs-youtube/blob/master/src/Youtube.js#L593

**Comment by gkatsev** [comment]
not sure what you mean but setting muted in video.js accepts a boolean to know whether muting is being turned on or off.

**Comment by mysuf** [comment]
In youtube.js:setMuted method is: `this.muted(true);` where `this` is probably instance of Youtube tech(not videoj.js player). And few rows above is this tech's muted() method defined without any arguments.
