### ISSUE TITLE
Not working with videojs 7.0.2

### ISSUE THREAD

**Issue by prateekrastogi** [videojs/videojs-youtube#498]
On using the plugin with videojs 7.0.2 I am getting error 'No compatible source was found for this media.'

**Comment by gkatsev** [comment]
Are you using a bundler like webpack? I think it's because we haven't added 7.x to the package.json yet, but it does work if added manually via `<scripts>`.

**Comment by prateekrastogi** [comment]
Yes, I am using webpack. Thanks for informing. Btw, any plans on adding 7.x to package.json on this plugin and default yeoman plugin generator?

**Comment by gkatsev** [comment]
Yeah, we should update the generator. I've updated this plugin yesterday with it. Should be available in v2.5.0.
