### ISSUE TITLE
player.playbackRate(rate) does not work

### ISSUE THREAD

**Issue by Bahir** [videojs/videojs-youtube#507]
The player.playbackRate(rate) does not work.
No errors, no messages, Just no effect.

**Comment by tomByrer** [comment]
I & another dev [also verify](https://github.com/PonyFrance/videojs-resolution-switcher/issues/3)

@gkatsev can you look at this please?  Some users, esp on mobile, get throttled when they use too much bandwidth, so is a bit important.

**Comment by gkatsev** [comment]
@tomByrer that looks like a separate issue. playbackRate is about playing back video at a faster/slower speed, which is different from which resolution to play.

**Comment by gkatsev** [comment]
Also, we haven't implemented a resolution selector but that might be something useful to have. We don't really have a good way for techs to add components to their players. We probably want to expose [youtube's playback qualities](https://developers.google.com/youtube/iframe_api_reference#Playback_quality) so it works with https://github.com/videojs/videojs-contrib-quality-levels.
But this should be another ticket.

**Comment by mig8447** [comment]
According to this update https://developers.google.com/youtube/iframe_api_reference#setPlaybackRate, it won't be possible to implement such thing anymore

**Comment by gkatsev** [comment]
Thanks. I think it's time to close this issue since the method doesn't exist.
