### ISSUE TITLE
TypeError: Cannot read property 'IS_IOS' of undefined

### ISSUE THREAD

**Issue by victorpfm** [videojs/videojs-youtube#509]
I am getting this error when I import videojs-youtube.

**Comment by cguess** [comment]
As posted in the related video.js bug: I'm getting the same error message using Yarn as my package manager. Safari and Chrome (MacOS 10.13.6) both throw the same errors.

**Comment by tapvt** [comment]
As (also) noted on related...

I can confirm the same with:

- `videojs@7.2.0`
- `videojs-youtube@7.5.0`
- OS: AWS Linux 2 (AWS Workspace)

**Comment by krishaamer** [comment]
Also having this problem. Anyone find a solution yet?

**Comment by gkatsev** [comment]
@haydnhkim figured out the issue here and submitted a PR. Going to merge some other ones and do a patch release today.

**Comment by gkatsev** [comment]
It's out in 2.5.1
