### ISSUE TITLE
Video not playing when loading in an iframe in desktop Chrome

### ISSUE THREAD

**Issue by alexdonskih** [videojs/videojs-youtube#532]
Hi.

I'm loading a `/videojs-youtube/examples/simple.html` example page from the repo in an iframe on a different domain. When I do this the video doesn't play and the loading indicator spins and doesn't stop. I see no javascript errors in the dev console. When I access the same file directly the video plays without any issues.

The issue occurs only in the latest desktop Chrome 72.0.3626.109. Other browsers don't seem to have it.

Here's a screen capture of how it looks like on my side:

https://www.youtube.com/watch?v=QBmre1vaLwI

Live example: https://jsfiddle.net/ws8tnc13/

Iframe source: https://alxd.ru/videojs-youtube/

I'll appreciate any help.

**Comment by alexdonskih** [comment]
I got help on Stackoverflow: https://stackoverflow.com/questions/54786686/videojs-youtube-video-not-playing-in-an-iframe-in-desktop-chrome

This had solved my problem.

**Comment by samueldjack** [comment]
I can confirm that the stackoverflow suggested solution fixed my problem too (in my case it was playing on Chrome desktop but not on mobile).

Btw, the solution is to add

     allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"

to the iframe that contains the code hosting the videojs player.
