### ISSUE TITLE
Global parameters example for v7

### ISSUE THREAD

**Issue by Guite** [videojs/videojs-youtube#541]
Hello,

the global parameters example is not working with video-js 7 anymore. I tried to replace the `setGlobalOptions` method by something like this:

```
videojs.options.youtube = {
    enablePrivacyEnhancedMode: true,
    ytControls: 2,
    ... more options
};
```
It does not work properly yet though. Maybe because my `script` section is too far below in the markup (don't know). Thus I currently specify the options as an attribute of the `video` tag, too.
Any idea how to further proceed with this approach?

**Comment by gkatsev** [comment]
It *should* work but can't say I tested it specifically. Have an example?

**Comment by Guite** [comment]
Thanks for the trigger @gkatsev . Luckily I can't reproduce the problem anymore.
Will close the issue. In case I see the behaviour again I am going to reopen it.
