### ISSUE TITLE
Investigate light-youtube-embed

### ISSUE THREAD

**Issue by gkatsev** [videojs/videojs-youtube#546]
https://github.com/paulirish/lite-youtube-embed

**Comment by txwizard** [comment]
Doesn't that defeat the purpose of having one HTML5 player to play them all?

**Comment by gkatsev** [comment]
Sort of. It's an interesting idea but doesn't actually help us here. This is because it hides the internals of the youtube player away from the user. If it exposed it, we could potentially use it.
Video.js probably should have a lite-videojs-embed type thing which allows you to embed just the poster image and a big play button and it won't load all of Video.js's code until a user hits play in which case it will download Video.js's javascript.
