### ISSUE TITLE
Current project status

### ISSUE THREAD

**Issue by DanielRuf** [videojs/videojs-youtube#547]
Is this project still actively maintained or are you looking for maintainers?

Or should we create a fork?

**Comment by gkatsev** [comment]
It's definitely not actively maintained but it isn't abandoned either. Help would definitely be appreciated and I'd definitely be up giving access to a new maintainer.
Unfortunately, we've been mostly focused on Video.js itself as well as VHS so haven't had much time to look more deeply at issues with this project, so, we mostly took a look when an issue had a lot of traction.
