### ISSUE TITLE
Doesn't trigger end / ended event

### ISSUE THREAD

**Issue by DanielRuf** [videojs/videojs-youtube#548]
https://codepen.io/DanielRuf/pen/xxbaPWw

See https://github.com/videojs/videojs-youtube/issues/261

**Comment by gkatsev** [comment]
I'm seeing `ended` trigger properly for when the video ended.

**Comment by DanielRuf** [comment]
But the play button is not reset at the end (shows pause icon).

**Comment by gkatsev** [comment]
Oh, looks like the issue is that the codepen uses Video.js 5 which doesn't do that. It is updated properly if using latest video.js: https://codepen.io/gkatsev/pen/BayOGdm

**Comment by DanielRuf** [comment]
We can not update to a newer version as it is part of a vendor file of a big client website.

Is there a simple solution to fix this?

**Comment by chrisjeon** [comment]
Has anyone figured this out yet?

**Comment by gkatsev** [comment]
Unfortunately, the latest youtube tech may not support Video.js 5. As mentioned in my previous comment using a newer Video.js with the youtube tech works fine.
If Video.js 5 is required we'd be happy to merge a fix assuming it's a reasonable change.
