### ISSUE TITLE
Stuck on loading with audio playing but no video

### ISSUE THREAD

**Issue by kylehi2222** [videojs/videojs-youtube#551]
Hi there,

Quite often my video player is getting stuck, either on the spinning loader with no audio playing, or the spinning loader and no audio playing. Both the poster image stuck.

 <img width="1680" alt="Screen Shot 2020-02-02 at 20 56 11" src="https://user-images.githubusercontent.com/57560006/73608483-77138880-45fe-11ea-8a47-785313c075bc.png">

https://growora.com/3795257/

This seems to happen in Chrome and Opera mainly, and is worse when the connection is dodgy. Any ideas on how I can fix this? $25 to the person who gives me the correct answer!

**Comment by gkatsev** [comment]
That doesn't seem to be using a Video.js player.
