### ISSUE TITLE
its not working

### ISSUE THREAD

**Issue by sreejithGravity** [videojs/videojs-youtube#563]
http://teamgravity.in/tests/videojs-youtube-master/examples/youtube-javascript.html
i just downloaded and and moved to server. but its not working

**Comment by jsite-pl** [comment]
Yours code looking for files in node_modules:
http://teamgravity.in/tests/videojs-youtube-master/**node_modules/video.js/dist/video.js** 
and not found that.

Add at begin of yours script:
`import videojs from 'video.js';`

And in styles.scss (if you uses sass):
`@import "~video.js/src/css/vjs.scss";`

Or use CDN links in HTML.
More info: https://videojs.com/getting-started/
