### ISSUE TITLE
How to disable share button

### ISSUE THREAD

**Issue by LCDBLUE** [videojs/videojs-youtube#568]
How to disable youtube share button in top right corner

**Comment by gkatsev** [comment]
I'm not sure it's possible to do. Not seeing anything here https://developers.google.com/youtube/iframe_api_reference for it.

**Comment by LCDBLUE** [comment]
> I'm not sure it's possible to do. Not seeing anything here https://developers.google.com/youtube/iframe_api_reference for it.

Thanks but Unable to find solution of this from above link
