### ISSUE TITLE
Controlbar not showing and play button not working in chrome.

### ISSUE THREAD

**Issue by samueleastdev** [videojs/videojs-youtube#570]
I seem to be having an issue with the controlbar not showing in Chrome and the play button does not work.

Here is an example: https://codepen.io/samueleastdev/full/gOrKqXZ

In Chrome, you can click the video to start it and it will play but the videojs controlbar ui does not show.

Works as expected in Firefox and Safari.

Anyone else having this issue with Chrome?

**Comment by richardhristov** [comment]
Can confirm with Firefox and Chrome on windows 7, works fine with windows 10 and works in IE 11 on windows 7.

**Comment by gkatsev** [comment]
I'm not able to reproduce in Chrome 85.0.4183.83 or 85.0.4183.121. I do see that clicking play will sometimes just stall and when it works it will take quite a long time before playback begins but if playback does begin the control bar seems to work.

**Comment by samueleastdev** [comment]
Thanks for taking a look both it seems to be working again now which is very weird I am not sure if it might have been related to a browser extension called skyload that I have deleted but the issue seemed to be only on my install of chrome. 

If I find any more details I will post here but I will close as there doesn't seem to be an issue with the plugin.

**Comment by NazarLysyi** [comment]
Have the same< play button not working in chrome(
