### ISSUE TITLE
What are the customVars we can use?

### ISSUE THREAD

**Issue by stefanomonteiro** [videojs/videojs-youtube#576]
Hi, where could i find the customVars that can be used? Ideally, I would like to eliminate the share buttons, title, more videos suggestion. Basically, every link that shows on hovering the video.

**Comment by gkatsev** [comment]
customVars allows you to pass in any of these that we don't already have an option for: https://developers.google.com/youtube/player_parameters#Parameters
Unfortunately, you're limited in the things you can turn off.
