### ISSUE TITLE
Hook Events in YouTube Tech

### ISSUE THREAD

**Issue by txwizard** [videojs/videojs-youtube#578]
I opened this issue against the YouTube tech repository so that I can use the issue number as part of the name of the branch that I am about to create against this repository. Having begun the work on the main [Video.js](https://github.com/videojs/video.js/) project, I discovered that I must modify both libraries to implement the changes required to satisfy [Issue 7081 - Hook Events in YouTube Tech](https://github.com/videojs/video.js/issues/7061#issue-792463788).

I expect to leave most of my comments on issue **7061** on the main **Video JS** project.

**Comment by gkatsev** [comment]
Unfortunately, this isn't something that we are able to support. Please use the Video.js events api for listening to events. For example `player.on('play', () => TrackEvent(' Begin Playing'))`
