### ISSUE TITLE
Infinite loading screen until I press play?

### ISSUE THREAD

**Issue by Nmoleo64** [videojs/videojs-youtube#580]
Hi everyone,

When I embed a youtube video using this plugin, it shows an infinite loading indicator until the big play button is pressed, at which point the video plays flawlessly. Is there any way to disable this loading indicator so that it doesn't confuse my users? Also, the autoplay doesn't seem to work, which may be related to this issue. Any ideas?

Thanks for your help

**Comment by Nmoleo64** [comment]
Never mind - I figured out the issue. It is caused by Firefox blocking autoplay by default. I will leave this up in case anyone else has the same problem.

**Comment by narration-sd** [comment]
So how did you work around this in Firefox, @Nmoleo64 ?

Could be useful for us to know :)

**Comment by Nmoleo64** [comment]
> So how did you work around this in Firefox, @Nmoleo64 Nicholas?
> 
> Could be useful for us to know :)

Unfortunately the only workaround I was able to find was to enable autoplay for my site in the Firefox settings. There doesn't seem to be a workaround I can do in the code since Firefox wants to block ads and news sites from playing video and audio.

**Comment by narration-sd** [comment]
Got a little intrigued, and found a page with some suggestions that might be useful.

https://mux.com/blog/video-autoplay-considered-harmful/
