### ISSUE TITLE
YT used in this manner

### ISSUE THREAD

**Issue by petrklus** [videojs/videojs-youtube#583]
Hi,

This may be a silly question, though I cannot seem to be able to find an answer for this - is this allowed by YouTube? Or is the simple existence of YT player API a de-facto licence for this to be allowed?

**Comment by gkatsev** [comment]
Yup, it's allowed given we use their provided API. People can mark videos as not viewable in player embeds should they not want their videos viewable outside youtube.com. The YouTube Terms of Service specifically grants other users license to the content via youtube services like embeds see "License to Other Users" on here https://www.youtube.com/static?gl=CA&template=terms
