### ISSUE TITLE
Css files is missing 

### ISSUE THREAD

**Issue by joshua750** [videojs/videojs-youtube#584]
Hello there no css files missing inside the dist folder

**Comment by gkatsev** [comment]
This project doesn't require any external CSS, the minimal amount of CSS uses is written out with javascript. If you've included the standard Video.js CSS, that's all you need.

**Comment by joshua750** [comment]
but there some files missing inside dist folder i need youtube embed code

**Comment by gkatsev** [comment]
Not sure I have anything live, but the examples in the repo show how to do it https://github.com/videojs/videojs-youtube/blob/master/examples/simple.html
