### ISSUE TITLE
Youtube.js V2.6.1 showing error in Eclipse IDE V2020-03 (4.15.0)

### ISSUE THREAD

**Issue by rxp113895gh** [videojs/videojs-youtube#585]
Need Video.js and Video-Youtube.js to work inside Spring .jsp with form (outside) and table (inner) containers. PFE source code  where configuration approach and scripting approach are both being attempted. However, Youtube.js (downloaded dist and was;nt edited by me) is showing error and causes hangup of Eclipse IDE. Attempted with Youtube.min.js but the test Youtube URL LiveStream is not showing and hence not playing in both approaches.  Please help.

[ProcessVideoForm.jsp.txt](https://github.com/videojs/videojs-youtube/files/6249299/ProcessVideoForm.jsp.txt)

**Comment by gkatsev** [comment]
What errors are you seeing? Are you including Video.js as well as videojs-youtube? And does Video.js get loaded first? Where are you downloading the dist file from?

**Comment by rxp113895gh** [comment]
What errors are you seeing? The moment I click on the file in Eclipse to see error or contents of file, causes hanging of EclipseIDE.
Are you including Video.js as well as videojs-youtube? Yes
And does Video.js get loaded first? Yes
Where are you downloading the dist file from? Github

**Comment by gkatsev** [comment]
Oh, totally forgot that we include the dist file in github, heh.
I'm not really sure what's happening with Eclipse. Are you getting playback in a browser? Any errors in a browser console?

**Comment by rxp113895gh** [comment]
2 Errors in BrowserConsole of Firefox are
TypeError: state.hideToggleDeferredTask is null         PictureInPictureChild.jsm:870:7
    onMouseLeaveVideo resource://gre/actors/PictureInPictureChild.jsm:870
    onMouseOut resource://gre/actors/PictureInPictureChild.jsm:673
    handleEvent resource://gre/actors/PictureInPictureChild.jsm:267

InvalidStateError: An attempt was made to use an object that is not, or is no longer, usable 2 PictureInPictureChild.jsm:150
    get docState resource://gre/actors/PictureInPictureChild.jsm:150
    onIntersection resource://gre/actors/PictureInPictureChild.jsm:345
    onIntersection self-hosted:1161

**Comment by rxp113895gh** [comment]
![ErrorInEclipse](https://user-images.githubusercontent.com/81808218/113497623-7dafcf80-9523-11eb-8dcf-5b7f4d12dee2.jpg)
I let hangup of eclipse timeout of the Youtube.js file so that I can see the error.  Please see above screenshot which shows error in every line, which means that either some high level declaration is missing or I need additional config in eclipse to view/use this file.  Please help.

**Comment by gkatsev** [comment]
Looks like your youtube.js file includes the actual github page instead of just the youtube source. Try re-downloading it from https://raw.githubusercontent.com/videojs/videojs-youtube/master/dist/Youtube.js

**Comment by rxp113895gh** [comment]
It appears that you have provided Ver2.6.0, please upload Ver2.6.1 (for my download and use).

**Comment by gkatsev** [comment]
That is version 2.6.1.
