### ISSUE TITLE
Not working with newer versions of video.js

### ISSUE THREAD

**Issue by viking1304** [videojs/videojs-youtube#597]
videojs-youtube 2.6.1 works perfectly fine with video.js versions up to 5.15.1

It doesn't work with 5.16.0 or any newer version of video.js

**Comment by malteneuss** [comment]
Until that is fixed: For those that really need Youtube support and are able to switch, i can highly recommend another open source player https://github.com/sampotts/plyr which comes with built-in in Youtube support and a quite clean API that just works.

**Comment by gkatsev** [comment]
videojs-youtube is working for me with latest Video.js. See this codepen for a live example: https://codepen.io/gkatsev/pen/poLqqvm

If you're on Video.js 5, you'll want to use an older version of videojs-youtube as newer versions don't assume video.js 5 support. Also, I would highly recommend updating your video.js versions, as the latest version of 5.x is almost 5 years old and there's been a lot of fixes and updates.
