### ISSUE TITLE
Full example?

### ISSUE THREAD

**Issue by HeadStudios** [videojs/videojs-youtube#602]
This is not working for me - I am getting the error:

Uncaught TypeError: Cannot read properties of undefined (reading 'browser')
    at Youtube.min.js:1:392
    at Youtube.min.js:1:307
    at Youtube.min.js:1:331
2video.min.js:12 VIDEOJS: ERROR: The "youtube" tech is undefined. Skipped browser support check for that tech.
(anonymous) @ video.min.js:12
video.min.js:12 VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) No compatible source was found for this media. bt

Also it is telling me I need to upgrade my browser (even though I am using latest version of Chrome)

https://share.getcloudapp.com/ApueRm1k

My Blade file is below:
https://gist.github.com/HeadStudios/9f947e16ecb13afe5b22b074518b5e3b

Please note even when I remove the
<source src="https://www.youtube.com/watch?v=xjS6SftYQaQ" type="youtube" />

tag the problem persists

Thank you!

**Comment by gkatsev** [comment]
You're including the youtube.min.js script before the video.js script. It needs to be included after.

**Comment by HeadStudios** [comment]
Thank you, I am able to embed YouTube using VideoJS
