### ISSUE TITLE
`videojs.extend` has been deprecated

### ISSUE THREAD

**Issue by boris-petrov** [videojs/videojs-youtube#604]
But it's been used [here](https://github.com/videojs/videojs-youtube/blob/v2.6.1/src/Youtube.js#L40).

**Comment by gkatsev** [comment]
Until/unless you upgrade to Video.js 8 you can ignore this. videojs-youtube will need to be updated for video.js 8 support and there hasn't been the bandwidth for doing that on the team yet.

**Comment by Bustillox** [comment]
Hello, do we have an estimated date as to when this is going to be worked on? thank you in advance!

**Comment by gkatsev** [comment]
Fix available in 3.0.0.
